[package]
name = "genetic-rs"
description = "A small crate for quickstarting genetic algorithm projects"
version = "0.2.1"
edition = "2021"
authors = ["HyperCodec"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/HyperCodec/genetic-rs"
repository = "https://github.com/HyperCodec/genetic-rs"
keywords = ["genetic", "algorithm", "rust"]
categories = ["algorithms", "science", "simulation"]

[features]
default = ["builtin", "genrand"]
builtin = []
crossover = []
genrand = []
neat = ["builtin"]
rayon = ["dep:rayon"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replace_with = "0.1.7"
rand = "0.8.5"
rayon = { version = "1.8.0", optional = true }
