[package]
name = "genetic-rs"
version = "0.1.0"
edition = "2021"
authors = ["HyperCodec"]
license = "MIT"

[features]
default = ["builtin"]
builtin = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replace_with = "0.1.7"
