[package]
name = "genetic-rs"
description = "A small crate for quickstarting genetic algorithm projects"
version = "0.1.0"
edition = "2021"
authors = ["HyperCodec"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/HyperCodec/genetic-rs"
repository = "https://github.com/HyperCodec/genetic-rs"
keywords = ["genetic", "algorithm", "rust"]
categories = ["algorithms", "science", "simulation"]

[features]
default = ["builtin", "genrand"]
builtin = []
sexual = ["dep:rand"]
genrand = ["dep:rand"]
rayon = ["dep:rayon"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replace_with = "0.1.7"
rand = { version = "0.8.5", optional = true }
rayon = { version = "1.8.0", optional = true }

[dev-dependencies]
fastrand = "2.0.1"
