[package]
name = "genetic-rs"
version = "0.1.0"
edition = "2021"
authors = ["HyperCodec"]
license = "MIT"

[features]
default = ["builtin"]
builtin = []
sexual = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
replace_with = "0.1.7"
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
rand = "0.8.5"