name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Unit Tests
        steps:
            - uses: actions/checkout@v4
            - name: Run cargo test
              run: cargo test --verbose