name: CI/CD

on:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: testing
        name: Run Unit Tests
        steps:
            - uses: actions/checkout@v4
            - name: Run cargo test
              run: cargo test --verbose --features crossover

    clippy:
        runs-on: ubuntu-latest
        name: Run Clippy Linting Checks
        steps:
            - uses: actions/checkout@v4
            - name: Run Clippy
              run: cargo clippy -- -D warnings