name: CI-CD

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: testing
        name: Unit Testing
        steps:
            - uses: actions/checkout@v4
            - name: Run cargo test
              run: cargo test --verbose --all-features

    clippy:
        runs-on: ubuntu-latest
        name: Clippy Linting Checks
        steps:
            - uses: actions/checkout@v4
            - name: Run Clippy
              run: cargo clippy --all-features -- -D warnings
    
    examples:
        runs-on: ubuntu-latest
        name: Run Examples
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - name: Run readme_ex example
              run: cargo run --example readme_ex --features builtin,genrand
            - name: Run crossover example
              run: cargo run --example crossover --features crossover,genrand
            - name: Run knockout example
              run: cargo run --example knockout --features knockout,crossover,genrand
            - name: Run derive example
              run: cargo run --example derive --features derive
            - name: Run speciation example
              run: cargo run --example speciation --features speciation,genrand

    fmt:
        runs-on: ubuntu-latest
        name: Formatting Checks
        steps:
            - uses: actions/checkout@v4
            - name: Run cargo fmt
              run: cargo fmt --check
